export const jobCatData = [
  { label: "IT-Sware/DB/QA/Web/Graphics/GIS", value: "1", id: "1" },
  { label: "IT-HWare/Networks/Systems", value: "2", id: "2" },
  { label: "Accounting/Auditing/Finance", value: "3", id: "3" },
  { label: "Banking/Insurance", value: "4", id: "4" },
  { label: "Sales/Marketing/Merchandising", value: "5", id: "5" },
  { label: "HR/Training", value: "6", id: "6" },
  { label: "Corporate Management/Analysts", value: "7", id: "7" },
  { label: "Office Admin/Secretary/Receptionist", value: "8", id: "8" },
  { label: "Civil Eng/Interior Design/Architecture", value: "9", id: "9" },
  { label: "IT-Telecoms", value: "10", id: "10" },
  { label: "Customer Relations/Public Relations", value: "11", id: "11" },
  { label: "Logistics/Warehouse/Transport", value: "12", id: "12" },
  { label: "Eng-Mech/Auto/Elec", value: "13", id: "13" },
  { label: "Manufacturing/Operations", value: "14", id: "14" },
  { label: "Media/Advert/Communication", value: "15", id: "15" },
  { label: "Hotels/Restaurants/Food", value: "16", id: "16" },
  { label: "Hospitality/Tourism", value: "17", id: "17" },
  { label: "Hospitality/Tourism", value: "18", id: "18" },
  { label: "Sports/Fitness/Recreation", value: "19", id: "19" },
  { label: "Hospital/Nursing/Healthcare", value: "20", id: "20" },
  { label: "Legal/Law", value: "21", id: "21" },
  { label: "Supervision/Quality Control", value: "22", id: "22" },
  { label: "Apparel/Clothing", value: "23", id: "23" },
  { label: "Ticketing/Airline/Marine", value: "24", id: "24" },
  { label: "Teaching/Academic/Library", value: "25", id: "25" },
  { label: "R&D/Science/Research", value: "26", id: "26" },
  { label: "Agriculture/Dairy/Environment", value: "27", id: "27" },
  { label: "Security", value: "28", id: "28" },
  { label: "Fashion/Design/Beauty", value: "29", id: "29" },
  { label: "International Development", value: "30", id: "30" },
  { label: "KPO/BPO", value: "31", id: "31" },
  { label: "Imports/Exports", value: "32", id: "32" },
];

export const jobTypeData = [
  { value: "full-time", label: "Full Time" },
  { value: "internship", label: "Internship" },
  { value: "contract", label: "Contract" },
  { value: "part-time", label: "Part Time" },
  { value: "freelance", label: "Freelance" },
];
//export const ACTION_INVALID = "This action is invalid!"
// import * as myConstClass from 'path/to/fileWithConstants';
